# generated by datamodel-codegen:
#   filename:  mood_schema.json
#   timestamp: 2026-04-14T11:57:50+00:00

from __future__ import annotations
from pydantic import BaseModel, ConfigDict


class Mood(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: str
    name: str
    mood: str
