# generated by datamodel-codegen:
#   filename:  poke_schema.json
#   timestamp: 2026-04-14T11:56:46+00:00

from __future__ import annotations
from pydantic import BaseModel


class Stats(BaseModel):
    attack: int | None = None
    defense: int | None = None
    hp: int | None = None
    special_attack: int | None = None
    special_defense: int | None = None
    speed: int | None = None


class Pokemon(BaseModel):
    id: int
    name: str
    weight: float | None = None
    height: float | None = None
    evo_condition: str | None = None
    evo_level: int | None = None
    generation: int | None = None
    stats: Stats | None = None
    types: list[str] | None = None
    evolutions: list[str] | None = None
    moves: list[str] | None = None


class PokeSpawn(BaseModel):
    date: str
    time: str
    location: str
    pokemon: Pokemon
