name: Package builder

run-name: "Building images ${{ github.sha }}"

on:
  push:
    branches: ['main']
    paths:
      - src/**/*
  pull_request:
    paths:
      - src/**/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile.api
            image_name: api
          - dockerfile: Dockerfile.pipeline
            image_name: pipeline

    steps:
      - uses: actions/checkout@v5

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.PROJECT_NAME }}

      - run: gcloud auth configure-docker ${{vars.REGION}}-docker.pkg.dev --quiet

      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_NAME }}/${{ vars.ARTIFACT_REPO }}/${{ matrix.image_name }}:latest
            ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_NAME }}/${{ vars.ARTIFACT_REPO }}/${{ matrix.image_name }}:${{ github.sha }}
