name: Build & Register Image

run-name: "Build & Register Image ${{ github.sha }}"

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [main]
    paths:
      - "src/"

jobs:
  build-and-register:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      TF_VAR_project_name: ${{ vars.PROJECT_NAME }}
      TF_VAR_region: ${{ vars.REGION }}
      TF_VAR_service_account_email: ${{ vars.SERVICE_ACCOUNT_EMAIL }}
      TF_VAR_artifact_repo_id: ${{ vars.ARTIFACT_REPO_ID }}
      TF_VAR_bucket_name: ${{ vars.BUCKET_NAME }}
      TF_VAR_instance_name: ${{ secrets.DB_INSTANCE_NAME }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_db_password: ${{ secrets.DB_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      #   uses: actions/checkout@v5

      # # 2️⃣ Set up Google Cloud SDK
      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v2
      #   with:
      #     project_id: ${{ env.PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     export_default_credentials: true

      # # 3️⃣ Configure Docker for Artifact Registry
      # - name: Configure Docker authentication
      #   run: |
      #     gcloud auth configure-docker europe-west4-docker.pkg.dev

      # # 4️⃣ Build and push Docker image for Cloud Run (amd64)
      # - name: Build and push Docker image
      #   run: |
      #     docker buildx build \
      #       --platform linux/amd64 \
      #       -t europe-west4-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest \
      #       --push .

      # # 5️⃣ Check if Cloud Run job exists
      # - name: Check if Cloud Run job exists
      #   id: job-check
      #   run: |
      #     if gcloud beta run jobs describe ${JOB_NAME} --region=${REGION} >/dev/null 2>&1; then
      #       echo "exists=true" >> $GITHUB_OUTPUT
      #     else
      #       echo "exists=false" >> $GITHUB_OUTPUT
      #     fi

      # # 6️⃣ Create or update Cloud Run job
      # - name: Create or update Cloud Run job
      #   run: |
      #     if [ "${{ steps.job-check.outputs.exists }}" = "true" ]; then
      #       echo "Updating existing Cloud Run job..."
      #       gcloud beta run jobs update ${JOB_NAME} \
      #         --image=europe-west4-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest \
      #         --region=${REGION} \
      #         --set-env-vars VAR1=${VAR1},VAR2=${VAR2}
      #     else
      #       echo "Creating new Cloud Run job..."
      #       gcloud beta run jobs create ${JOB_NAME} \
      #         --image=europe-west4-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest \
      #         --region=${REGION} \
      #         --set-env-vars VAR1=${VAR1},VAR2=${VAR2}
      #     fi
