name: CI Pipeline for GCP infrastructure

run-name: "Infra update ${{ github.sha }} on ${{ github.ref }}"

on: [push]

defaults:
  run:
    working-directory: infra/pipeline

jobs:
  validate-lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6

      - name: Install tf linter
      - uses: terraform-linters/setup-tflint@v6
        with:
          cache: true

      - name: Install tf plugins
      - run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Lint
      - run: tflint -f compact

      - name: Format
        run: terraform fmt -check -recursive

      - name: Init
        run: terraform init -backend=false

      - name: Validate
        run: terraform validate
