name: CI Format check

run-name: "Format check ${{ github.sha }} on ${{ github.ref }}"

on:
  push:
    paths:
      - "./src/**/*"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Format check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
          args: "format --diff --output-format=github --preview"
