name: CI Pipeline for GCP

run-name: "Infra update ${{ github.sha }} on ${{ github.ref }}"

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [main]
    paths:
      - "infra/pipeline/**/*"

defaults:
  run:
    working-directory: infra/pipeline

env:
  TF_VAR_project_name: ${{ vars.PROJECT_NAME }}
  TF_VAR_region: ${{ vars.REGION }}
  TF_VAR_service_account_email: ${{ vars.SERVICE_ACCOUNT_EMAIL }}
  TF_VAR_artifact_repo_id: ${{ vars.ARTIFACT_REPO_ID }}
  TF_VAR_bucket_name: ${{ vars.BUCKET_NAME }}
  TF_VAR_elt_image_name: ${{ vars.ELT_IMAGE_NAME }}
  #
  TF_VAR_instance_name: ${{ secrets.DB_INSTANCE_NAME }}
  TF_VAR_db_name: ${{ secrets.DB_NAME }}
  TF_VAR_db_user: ${{ secrets.DB_USER }}
  TF_VAR_db_password: ${{ secrets.DB_PASS }}

jobs:
  lint:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6

      - name: Install tf linter
        uses: terraform-linters/setup-tflint@v6
        with:
          cache: true

      - name: Install tf plugins
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Lint
        run: tflint --recursive -f compact

  format:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6

      - name: Format
        run: terraform fmt -check -recursive

  validate:
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6

      - name: Init
        run: terraform init -backend=false

      - name: Validate
        run: terraform validate

  plan:
    needs: [lint, format, validate]
    if: github.event.pull_request.merged != true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        timeout-minutes: 5
        run: terraform plan -no-color -input=false -lock-timeout=60s

  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        timeout-minutes: 5
        run: terraform plan -no-color -input=false -lock-timeout=60s

      - name: Terraform Apply
        if: ${{ success() }}
        run: terraform apply -auto-approve
